"""
All Pydantic models for EgoVault v2.

Single source of truth for data contracts.
The LLM fills NoteContentInput only — everything else is system-generated.
"""

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator
from typing import Literal


# ============================================================
# LLM CONTRACT — the ONLY schema the LLM fills in
# All fields validated against system.yaml taxonomy at runtime
# ============================================================

class NoteContentInput(BaseModel):
    """Fields filled by the LLM (or manually by the user). No system metadata here."""
    title: str = Field(min_length=3, max_length=200)
    docstring: str = Field(max_length=300, description="3-line max: what, why, thesis")
    body: str = Field(min_length=10)
    note_type: str | None = None      # validated against system.yaml:taxonomy.note_types
    source_type: str | None = None    # validated against system.yaml:taxonomy.source_types
    tags: list[str] = Field(min_length=1, max_length=10)
    url: str | None = None            # only for source-less notes (source_uid IS NULL)

    @field_validator("tags")
    @classmethod
    def tags_must_be_kebab(cls, v: list[str]) -> list[str]:
        import re
        for tag in v:
            if not tag:
                raise ValueError("tags must not contain empty strings")
            if len(tag) > 80:
                raise ValueError(f"tag '{tag}' exceeds 80 characters")
            if tag != tag.lower():
                raise ValueError(f"tag '{tag}' must be lowercase")
            try:
                tag.encode("ascii")
            except UnicodeEncodeError:
                raise ValueError(f"tag '{tag}' must contain only ASCII characters (no accents)")
            if not re.match(r"^[a-z0-9][a-z0-9-]*[a-z0-9]$|^[a-z0-9]$", tag):
                raise ValueError(
                    f"tag '{tag}' must be kebab-case: only [a-z0-9] and hyphens, "
                    "no leading/trailing hyphens, no spaces or underscores"
                )
        if len(v) != len(set(v)):
            raise ValueError("tags must not contain duplicates")
        return v

    @model_validator(mode="before")
    @classmethod
    def validate_taxonomy(cls, values: dict, info) -> dict:
        if not info or not info.context:
            return values
        taxonomy = info.context.get("taxonomy")
        if taxonomy is None:
            return values
        note_type = values.get("note_type")
        if note_type is not None and note_type not in taxonomy.note_types:
            raise ValueError(
                f"note_type '{note_type}' is not in taxonomy.note_types: {taxonomy.note_types}"
            )
        source_type = values.get("source_type")
        if source_type is not None and source_type not in taxonomy.source_types:
            raise ValueError(
                f"source_type '{source_type}' is not in taxonomy.source_types: {taxonomy.source_types}"
            )
        return values


# ============================================================
# SYSTEM FIELDS — generated by system, never by LLM
# ============================================================

class NoteSystemFields(BaseModel):
    uid: str                            # UUID4 from core/uid.py — IMMUTABLE
    date_created: str                   # ISO date — IMMUTABLE
    source_uid: str | None = None
    slug: str                           # derived from title by make_slug()
    generation_template: str | None = None
                                        # set by calling workflow BEFORE the LLM call
                                        # validated against system.yaml:taxonomy.generation_templates
                                        # NULL for manually written notes
                                        # LLM never sets or modifies this field
                                        # watcher never syncs this from frontmatter
                                        # updatable only via regeneration workflow (human-triggered)


class Note(NoteSystemFields, NoteContentInput):
    """Full note record = system fields + LLM content."""
    model_config = ConfigDict(extra="ignore")
    date_modified: str
    rating: int | None = Field(None, ge=1, le=5)  # user-only signal, semantics open
    sync_status: str = "synced"                    # synced|needs_re_embedding|embedding
    status: str = "active"       # approval state: draft (auto-generated) | active (human-approved)


# ============================================================
# SOURCE SCHEMAS
# ============================================================

class SourceCreateInput(BaseModel):
    """Input to register a new source before processing."""
    source_type: str              # validated against taxonomy
    url: str | None = None
    title: str | None = None
    author: str | None = None
    date_source: str | None = None
    raw_metadata: dict | None = None


class Source(BaseModel):
    """Full source record from DB."""
    model_config = ConfigDict(extra="ignore")
    uid: str
    slug: str
    source_type: str
    status: str
    url: str | None = None
    title: str | None = None
    author: str | None = None
    date_added: str
    date_source: str | None = None
    media_path: str | None = None
    transcript: str | None = None
    raw_metadata: str | None = None


# ============================================================
# TOOL RESULT TYPES — one per tool output
# ============================================================

class TranscriptResult(BaseModel):
    text: str
    language: str
    duration_seconds: float | None = None


class CompressResult(BaseModel):
    output_path: str
    original_size_bytes: int
    compressed_size_bytes: int


class SubtitleResult(BaseModel):
    text: str
    language: str
    source: Literal["subtitles", "transcription"]


class AudioFileResult(BaseModel):
    output_path: str


class ChunkResult(BaseModel):
    uid: str
    position: int
    content: str
    token_count: int


class SummaryResult(BaseModel):
    text: str
    chunk_count: int


class NoteResult(BaseModel):
    note: Note
    markdown_path: str


class FinalizeResult(BaseModel):
    source_uid: str
    new_status: str
    media_moved_to: str | None = None


class SearchResult(BaseModel):
    note_uid: str | None = None
    source_uid: str | None = None
    chunk_uid: str | None = None
    content: str
    title: str
    distance: float


class SearchFilters(BaseModel):
    source_type: str | None = None
    note_type: str | None = None
    tags: list[str] | None = None
    date_from: str | None = None
    date_to: str | None = None


class ExportResult(BaseModel):
    output_path: str
    format: Literal["typst", "mermaid"]


class EmbedNoteResult(BaseModel):
    note_uid: str
    embedding_dim: int
