"""
Markdown file generator for EgoVault v2.

Generates .md files from Note DB records.
Owns the frontmatter format (SYSTEM + CONTENT zones).
Never reads from disk — always writes from DB state.

Frontmatter zones (spec section 5.3):
  SYSTEM — uid, date_created, source_uid, generation_template (immutable)
  CONTENT — date_modified, note_type, source_type, rating, tags, url (editable)
"""

from pathlib import Path
from core.schemas import Note


def write_note(note: Note, vault_path: Path) -> Path:
    """
    Generate a Markdown file from a Note record.
    Returns the path to the written file. Overwrites if exists.
    """
    content = build_markdown(note)
    file_path = vault_path / f"{note.slug}.md"
    file_path.write_text(content, encoding="utf-8")
    return file_path


def build_frontmatter(note: Note) -> str:
    """
    Build the YAML frontmatter string for a note.
    SYSTEM fields (uid, date_created, source_uid, generation_template) — marked DO NOT EDIT.
    CONTENT fields (date_modified, note_type, source_type, rating, tags, url) — editable.
    """
    lines = ["---"]

    # SYSTEM zone
    lines.append("# SYSTEM — generated by vault_writer.py")
    lines.append("# DO NOT EDIT — changes will be ignored by sync watcher")
    lines.append(f"uid: {note.uid}")
    lines.append(f"date_created: {note.date_created}")
    if note.source_uid is not None:
        lines.append(f"source_uid: {note.source_uid}")
    if note.generation_template is not None:
        lines.append(f"generation_template: {note.generation_template}")

    lines.append("")

    # CONTENT zone
    lines.append("# CONTENT — editable in Obsidian")
    lines.append("# Changes synced back to DB if uid is intact")
    lines.append(f"date_modified: {note.date_modified}")
    if note.note_type is not None:
        lines.append(f"note_type: {note.note_type}")
    if note.source_type is not None:
        lines.append(f"source_type: {note.source_type}")
    if note.rating is not None:
        lines.append(f"rating: {note.rating}")
    if note.tags:
        lines.append(f"tags: [{', '.join(note.tags)}]")
    if note.url is not None:
        safe_url = note.url.replace('"', '\\"')
        lines.append(f'url: "{safe_url}"')

    lines.append("---")
    return "\n".join(lines)


def build_markdown(note: Note) -> str:
    """Assemble full Markdown content: frontmatter + H1 title + docstring blockquote + body."""
    parts = [build_frontmatter(note), ""]
    parts.append(f"# {note.title}")
    parts.append("")
    if note.docstring:
        parts.append(f"> {note.docstring}")
        parts.append("")
    parts.append(note.body)
    return "\n".join(parts)
